source "https://rubygems.org"

gem "jekyll"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "octopress-minify-html"
  gem "jekyll-assets"
end

# needed for jekyll-assets
gem "sprockets", "~> 3.7"
